-- Dummy reference data for Dormitory Management System
-- Run in Supabase Dashboard → SQL Editor (after initial_schema migration)
-- Re-running clears and re-inserts the same sample rows.

truncate table public.payments, public.assignments, public.students, public.rooms restart identity cascade;

-- Allow fixed ids (matches app dummy data ids 1–10, etc.)
alter table public.rooms alter column id set generated by default;
alter table public.students alter column id set generated by default;
alter table public.assignments alter column id set generated by default;
alter table public.payments alter column id set generated by default;

-- Rooms
insert into public.rooms (id, room_number, floor, capacity, current_occupancy, status)
overriding system value
values
  (1, '101', 1, 2, 2, 'full'),
  (2, '102', 1, 3, 1, 'partial'),
  (3, '103', 1, 2, 1, 'partial'),
  (4, '201', 2, 4, 2, 'partial'),
  (5, '202', 2, 2, 1, 'partial'),
  (6, '203', 2, 2, 0, 'available'),
  (7, '301', 3, 6, 0, 'available'),
  (8, '302', 3, 2, 0, 'available');

-- Students
insert into public.students (id, name, student_id, course, department, contact_number, assigned_room_id)
overriding system value
values
  (1, 'Alice Johnson', 'STU001', 'Computer Science', 'Engineering', '555-0101', 1),
  (2, 'Bob Smith', 'STU002', 'Mathematics', 'Science', '555-0102', 1),
  (3, 'Charlie Davis', 'STU003', 'Physics', 'Science', '555-0103', null),
  (4, 'Diana Evans', 'STU004', 'Literature', 'Arts', '555-0104', 2),
  (5, 'Ethan Foster', 'STU005', 'History', 'Arts', '555-0105', null),
  (6, 'Fiona Green', 'STU006', 'Biology', 'Science', '555-0106', 3),
  (7, 'George Harris', 'STU007', 'Chemistry', 'Science', '555-0107', 4),
  (8, 'Hannah Ivey', 'STU008', 'Business', 'Business', '555-0108', 4),
  (9, 'Ian Jones', 'STU009', 'Economics', 'Business', '555-0109', null),
  (10, 'Julia King', 'STU010', 'Psychology', 'Social Science', '555-0110', 5);

-- Assignments
insert into public.assignments (id, student_id, room_id, assigned_at)
overriding system value
values
  (1, 1, 1, '2026-05-15 08:00:00+00'),
  (2, 2, 1, '2026-05-15 10:00:00+00'),
  (3, 4, 2, '2026-05-16 08:00:00+00'),
  (4, 6, 3, '2026-05-16 12:00:00+00'),
  (5, 7, 4, '2026-05-17 08:00:00+00'),
  (6, 8, 4, '2026-05-17 10:00:00+00'),
  (7, 10, 5, '2026-05-17 14:00:00+00');

-- Payments (dates relative to 2026-05-18 reference day in the app)
insert into public.payments (id, student_id, amount, description, due_date, paid_date, status, period)
overriding system value
values
  (1, 1, 4500, 'Dormitory Fee', '2026-04-18', '2026-04-20', 'paid', 'Jan 2026'),
  (2, 2, 4500, 'Dormitory Fee', '2026-04-18', '2026-04-23', 'paid', 'Jan 2026'),
  (3, 4, 3800, 'Dormitory Fee', '2026-04-18', null, 'overdue', 'Jan 2026'),
  (4, 6, 4500, 'Dormitory Fee', '2026-04-18', '2026-04-28', 'paid', 'Jan 2026'),
  (5, 7, 4200, 'Dormitory Fee', '2026-04-18', null, 'overdue', 'Jan 2026'),
  (6, 8, 4200, 'Dormitory Fee', '2026-04-18', '2026-05-03', 'paid', 'Jan 2026'),
  (7, 10, 4500, 'Dormitory Fee', '2026-04-18', '2026-05-08', 'paid', 'Jan 2026'),
  (8, 1, 4500, 'Dormitory Fee', '2026-05-23', null, 'pending', 'Feb 2026'),
  (9, 2, 4500, 'Dormitory Fee', '2026-05-23', null, 'pending', 'Feb 2026'),
  (10, 4, 3800, 'Dormitory Fee', '2026-05-23', null, 'pending', 'Feb 2026'),
  (11, 6, 4500, 'Dormitory Fee', '2026-05-23', null, 'pending', 'Feb 2026'),
  (12, 7, 4200, 'Dormitory Fee', '2026-05-23', null, 'pending', 'Feb 2026'),
  (13, 1, 500, 'Maintenance Fee', '2026-05-03', '2026-05-06', 'paid', 'Jan 2026'),
  (14, 3, 200, 'Registration Fee', '2026-05-28', null, 'pending', 'Feb 2026'),
  (15, 5, 200, 'Registration Fee', '2026-05-13', null, 'overdue', 'Jan 2026');

select setval(pg_get_serial_sequence('public.rooms', 'id'), (select max(id) from public.rooms));
select setval(pg_get_serial_sequence('public.students', 'id'), (select max(id) from public.students));
select setval(pg_get_serial_sequence('public.assignments', 'id'), (select max(id) from public.assignments));
select setval(pg_get_serial_sequence('public.payments', 'id'), (select max(id) from public.payments));
